import {useEffect,useState} from 'react';import {Link} from 'react-router-dom';import {useAuth} from '../context/AuthContext.jsx';import {supabase,uploadImage} from '../services/supabase.js';import {defaultSettings,getBusinessSettings,saveBusinessSettings} from '../services/businessSettings.js';import IdentitySettings from '../components/IdentitySettings.jsx';import CmsSectionEditor from '../components/CmsSectionEditor.jsx';import AccountSettings from '../components/AccountSettings.jsx';import '../styles/admin.css';import '../styles/identity.css';import '../styles/cms-sections.css';
const empty={nombre:'',descripcion:'',precio:'',categoria_id:'',imagen:'',disponible:true,destacado:false};
export default function Admin(){const {user,signOut}=useAuth();const [tab,setTab]=useState('resumen'),[products,setProducts]=useState([]),[categories,setCategories]=useState([]),[promos,setPromos]=useState([]),[promoForm,setPromoForm]=useState({titulo:'',descripcion:'',imagen:'',activa:true}),[editingPromo,setEditingPromo]=useState(null),[answers,setAnswers]=useState([]),[config,setConfig]=useState(defaultSettings),[form,setForm]=useState(empty),[editing,setEditing]=useState(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 async function load(){try{const [p,c,r,a,business]=await Promise.all([supabase.from('productos').select('*,categorias(nombre)').order('created_at',{ascending:false}),supabase.from('categorias').select('*').order('orden'),supabase.from('promociones').select('*').order('fecha',{ascending:false}),supabase.from('respuestas_chatbot').select('*').order('clave'),getBusinessSettings()]);const firstError=[p,c,r,a].find(x=>x.error)?.error;if(firstError)throw firstError;setProducts(p.data||[]);setCategories(c.data||[]);setPromos(r.data||[]);setConfig({...defaultSettings,...business.data});setAnswers(a.data||[])}catch(error){setNotice(`No fue posible cargar el panel: ${error.message}`)}}
 useEffect(()=>{load()},[]);const flash=m=>{setNotice(m);setTimeout(()=>setNotice(''),2800)};
 async function saveProduct(e){e.preventDefault();setBusy(true);const payload={...form,precio:Number(form.precio)};const q=editing?supabase.from('productos').update(payload).eq('id',editing):supabase.from('productos').insert(payload);const {error}=await q;setBusy(false);if(error)return flash(error.message);setForm(empty);setEditing(null);await load();flash('Producto guardado correctamente')}
 function edit(p){setForm({nombre:p.nombre,descripcion:p.descripcion||'',precio:p.precio,categoria_id:p.categoria_id||'',imagen:p.imagen||'',disponible:p.disponible,destacado:p.destacado});setEditing(p.id);setTab('productos');scrollTo({top:0,behavior:'smooth'})}
 async function remove(id){if(!confirm('¿Eliminar este producto?'))return;await supabase.from('productos').delete().eq('id',id);load()}
 async function image(e){const file=e.target.files[0];if(!file)return;setBusy(true);try{setForm({...form,imagen:await uploadImage(file)})}catch(err){flash(err.message)}setBusy(false)}
 async function saveConfig(e){e.preventDefault();setBusy(true);try{setConfig({...defaultSettings,...await saveBusinessSettings(config)});flash('Cambios guardados y publicados')}catch(error){flash(error.message)}finally{setBusy(false)}}
 async function uploadSetting(file,folder,key,returnOnly=false){setBusy(true);try{const url=await uploadImage(file,folder);if(!returnOnly)setConfig(current=>({...current,[key]:url}));flash('Imagen cargada. Guarda los cambios para publicarla.');return url}catch(error){flash(error.message);return ''}finally{setBusy(false)}}
 async function uploadGallery(file,folder,key){setBusy(true);try{const url=await uploadImage(file,folder);setConfig(current=>{let images=[];try{images=JSON.parse(current[key]||'[]')}catch{images=String(current[key]||'').split(',').filter(Boolean)}return {...current,[key]:JSON.stringify([...images,url])}});flash('Imagen cargada. Guarda la galería para publicarla.')}catch(error){flash(error.message)}finally{setBusy(false)}}
 async function addIdentityCategory(nombre){const existing=categories.find(category=>category.nombre.toLowerCase()===nombre.toLowerCase());if(existing){flash('La categoría ya existe y fue agregada a destacados');return existing}setBusy(true);const {data,error}=await supabase.from('categorias').insert({nombre,orden:categories.length+1}).select().single();setBusy(false);if(error){flash(error.message);throw error}setCategories(current=>[...current,data]);flash('Categoría venezolana agregada');return data}
 async function togglePromo(p){await supabase.from('promociones').update({activa:!p.activa}).eq('id',p.id);load()}
 async function savePromo(e){e.preventDefault();const query=editingPromo?supabase.from('promociones').update(promoForm).eq('id',editingPromo):supabase.from('promociones').insert(promoForm);const {error}=await query;if(error)return flash(error.message);setPromoForm({titulo:'',descripcion:'',imagen:'',activa:true});setEditingPromo(null);load();flash(editingPromo?'Promoción actualizada':'Promoción publicada')}
 function editPromo(p){setEditingPromo(p.id);setPromoForm({titulo:p.titulo,descripcion:p.descripcion||'',imagen:p.imagen||'',activa:p.activa});scrollTo({top:0,behavior:'smooth'})}
 async function promoImage(e){const file=e.target.files[0];if(!file)return;setBusy(true);try{setPromoForm({...promoForm,imagen:await uploadImage(file,'promociones')})}catch(err){flash(err.message)}setBusy(false)}
 async function deletePromo(id){if(confirm('¿Eliminar esta promoción?')){await supabase.from('promociones').delete().eq('id',id);load()}}
 async function saveAnswers(){const creating=answers.some(answer=>!answer.id);const clean=answers.map(answer=>({...answer,clave:answer.clave?.trim(),respuesta:answer.respuesta?.trim()}));if(clean.some(answer=>!answer.clave||!answer.respuesta))return flash('La clave y la respuesta son obligatorias');const keys=clean.map(answer=>answer.clave);if(new Set(keys).size!==keys.length)return flash('No se permiten claves duplicadas');const payload=clean.map(({id,clave,respuesta})=>id?{id,clave,respuesta}:{clave,respuesta});const {error}=await supabase.from('respuestas_chatbot').upsert(payload,{onConflict:'clave'});if(error)return flash(error.code==='23505'?'No se permiten claves duplicadas':error.message);await load();flash(creating?'Respuesta creada correctamente':'Respuesta actualizada correctamente')}
 async function deleteAnswer(answer,index){if(!confirm('¿Eliminar esta respuesta?'))return;if(answer.id){const {error}=await supabase.from('respuestas_chatbot').delete().eq('id',answer.id);if(error)return flash(error.message)}setAnswers(current=>current.filter((_,itemIndex)=>itemIndex!==index));flash('Respuesta eliminada correctamente')}
 async function toggleFeaturedProduct(product){const {error}=await supabase.from('productos').update({destacado:!product.destacado}).eq('id',product.id);if(error)return flash(error.message);setProducts(current=>current.map(item=>item.id===product.id?{...item,destacado:!item.destacado}:item));flash('Productos destacados actualizados')}
 const nav=[['resumen','Inicio'],['productos','Productos'],['promociones','Promociones'],['pagina','Página principal'],['nosotros','Nosotros'],['diseno','Diseño'],['contacto','Contacto'],['identidad','🇻🇪 Identidad del negocio'],['chatbot','Chatbot'],['cuenta','⚙️ Configuración']];
 return <main className="admin-shell"><aside className="admin-sidebar"><div className="admin-logo"><span>PC</span><div><b>Pedacito de Cielo</b><small>Administrador</small></div></div><nav>{nav.map(n=><button key={n[0]} className={tab===n[0]?'active':''} onClick={()=>setTab(n[0])}>{n[1]}</button>)}</nav><div className="admin-user"><small>Conectado como</small><b>{user?.email||'Administrador'}</b><button onClick={signOut}>Cerrar sesión</button></div></aside><section className="admin-main"><header><div><small>Panel de control</small><h1>{nav.find(n=>n[0]===tab)?.[1]}</h1></div><Link to="/" target="_blank">Ver sitio ↗</Link></header>{notice&&<div className="cms-notice">{notice}</div>}
 {tab==='resumen'&&<><div className="stats"><article><span>Productos</span><b>{products.length}</b><small>{products.filter(p=>p.disponible).length} disponibles</small></article><article><span>Categorías</span><b>{categories.length}</b><small>Organizan el catálogo</small></article><article><span>Promociones activas</span><b>{promos.filter(p=>p.activa).length}</b><small>Visibles en el sitio</small></article></div><section className="admin-card"><div className="card-title"><div><h2>Últimos productos</h2><p>Contenido agregado recientemente.</p></div><button onClick={()=>setTab('productos')}>Gestionar productos →</button></div><ProductTable products={products.slice(0,5)} edit={edit} remove={remove}/></section></>}
 {tab==='productos'&&<><section className="admin-card product-form"><div className="card-title"><div><h2>{editing?'Editar producto':'Nuevo producto'}</h2><p>Los cambios aparecen inmediatamente en el catálogo.</p></div>{editing&&<button onClick={()=>{setEditing(null);setForm(empty)}}>Cancelar</button>}</div><form onSubmit={saveProduct} className="cms-form"><label>Nombre<input required value={form.nombre} onChange={e=>setForm({...form,nombre:e.target.value})}/></label><label>Precio CLP<input required type="number" value={form.precio} onChange={e=>setForm({...form,precio:e.target.value})}/></label><label className="wide">Descripción<textarea value={form.descripcion} onChange={e=>setForm({...form,descripcion:e.target.value})}/></label><label>Categoría<select required value={form.categoria_id} onChange={e=>setForm({...form,categoria_id:e.target.value})}><option value="">Seleccionar</option>{categories.map(c=><option value={c.id} key={c.id}>{c.nombre}</option>)}</select></label><label>Imagen<input type="file" accept="image/*" onChange={image}/></label>{form.imagen&&<img className="image-preview" src={form.imagen} alt="Vista previa"/>}<label className="check"><input type="checkbox" checked={form.disponible} onChange={e=>setForm({...form,disponible:e.target.checked})}/> Disponible</label><label className="check"><input type="checkbox" checked={form.destacado} onChange={e=>setForm({...form,destacado:e.target.checked})}/> Destacado</label><button className="cms-primary" disabled={busy}>{busy?'Guardando…':'Guardar producto'}</button></form></section><section className="admin-card"><div className="card-title"><div><h2>Todos los productos</h2><p>{products.length} elementos en el catálogo.</p></div></div><ProductTable products={products} edit={edit} remove={remove}/></section></>}
 {tab==='promociones'&&<><section className="admin-card"><div className="card-title"><div><h2>{editingPromo?'Editar promoción':'Nueva promoción'}</h2><p>Agrega una campaña visible en la página principal.</p></div>{editingPromo&&<button onClick={()=>{setEditingPromo(null);setPromoForm({titulo:'',descripcion:'',imagen:'',activa:true})}}>Cancelar</button>}</div><form className="cms-form" onSubmit={savePromo}><label>Título<input required value={promoForm.titulo} onChange={e=>setPromoForm({...promoForm,titulo:e.target.value})}/></label><label>Imagen<input type="file" accept="image/*" onChange={promoImage}/></label><label className="wide">Descripción<textarea value={promoForm.descripcion} onChange={e=>setPromoForm({...promoForm,descripcion:e.target.value})}/></label>{promoForm.imagen&&<img className="image-preview" src={promoForm.imagen} alt="Vista previa de promoción"/>}<button className="cms-primary" disabled={busy}>{editingPromo?'Guardar promoción':'Publicar promoción'}</button></form></section><section className="admin-card"><div className="card-title"><div><h2>Promociones</h2><p>Activa, pausa, edita o elimina campañas.</p></div></div><div className="promo-list">{promos.map(p=><article key={p.id}><img src={p.imagen||'/images/productos/torta-chocolate.jpg'} alt=""/><div><small>{p.activa?'Publicada':'Pausada'}</small><h3>{p.titulo}</h3><p>{p.descripcion}</p></div><div><button onClick={()=>editPromo(p)}>Editar</button><button onClick={()=>togglePromo(p)}>{p.activa?'Pausar':'Activar'}</button><button onClick={()=>deletePromo(p.id)}>Eliminar</button></div></article>)}{!promos.length&&<div className="empty-state">Aún no hay promociones.</div>}</div></section></>}
 {['pagina','nosotros','diseno','contacto','chatbot'].includes(tab)&&<CmsSectionEditor mode={tab} config={config} setConfig={setConfig} answers={answers} setAnswers={setAnswers} onSave={saveConfig} onSaveAnswers={saveAnswers} onDeleteAnswer={deleteAnswer} onNotify={flash} onUpload={uploadSetting} busy={busy}/>}
 {tab==='identidad'&&<IdentitySettings config={config} setConfig={setConfig} categories={categories} products={products} answers={answers} setAnswers={setAnswers} onSave={saveConfig} onSaveAnswers={saveAnswers} onAddCategory={addIdentityCategory} onToggleFeatured={toggleFeaturedProduct} onUploadMain={uploadSetting} onUploadGallery={uploadGallery} busy={busy}/>}
 {tab==='cuenta'&&<AccountSettings/>}
 </section></main>}
function ProductTable({products,edit,remove}){return <div className="cms-table">{products.map(p=><article key={p.id}><img src={p.imagen||'/images/productos/marraqueta.jpg'}/><div><b>{p.nombre}</b><small>{p.categorias?.nombre||'Sin categoría'}</small></div><strong>${Number(p.precio).toLocaleString('es-CL')}</strong><span className={p.disponible?'status on':'status'}>{p.disponible?'Disponible':'Oculto'}</span><div className="row-actions"><button onClick={()=>edit(p)}>Editar</button><button onClick={()=>remove(p.id)}>Eliminar</button></div></article>)}</div>}
