import {useEffect,useState} from 'react';import {Link} from 'react-router-dom';import {useAuth} from '../context/AuthContext.jsx';import {supabase,uploadImage} from '../services/supabase.js';import {defaultSettings,getBusinessSettings,saveBusinessSettings} from '../services/businessSettings.js';import IdentitySettings from '../components/IdentitySettings.jsx';import CmsSectionEditor from '../components/CmsSectionEditor.jsx';import AccountSettings from '../components/AccountSettings.jsx';import AnalyticsPanel from '../components/AnalyticsPanel.jsx';import CrmPanel from '../components/CrmPanel.jsx';import NewsSettings from '../components/NewsSettings.jsx';import '../styles/admin.css';import '../styles/identity.css';import '../styles/cms-sections.css';
import { isModuleEnabled } from '../config/siteConfig.js';
const productLabels=['Más vendido','Favorito','Recomendado','Nuevo'];
const empty={nombre:'',descripcion:'',precio:'',categoria_id:'',imagen:'',disponible:true,estado:'disponible',etiqueta:'',destacado:false,orden:0};
const emptyPromo={titulo:'',descripcion:'',imagen:'',activa:true,fecha_inicio:'',fecha_termino:''};
const productState=(product)=>product.estado||(product.disponible===false?'agotado':'disponible');
const moduleTabs={analitica:'analytics',crm:'crm',promociones:'promociones',novedades:'novedades',chatbot:'chatbot'};
const navGroups=[
 {label:'Inicio',items:[['resumen','Resumen'],['analitica','Analítica'],['crm','CRM']]},
 {label:'Gestión comercial',items:[['productos','Productos'],['promociones','Promociones']]},
 {label:'Contenido',items:[['pagina','Página principal'],['novedades','Novedades'],['nosotros','Nosotros'],['contacto','Contacto'],['identidad','🇻🇪 Identidad del negocio'],['chatbot','Chatbot']]},
 {label:'Configuración',items:[['diseno','Diseño'],['cuenta','Cuenta administrador']]},
].map(group=>({...group,items:group.items.filter(([tab])=>!moduleTabs[tab]||isModuleEnabled(moduleTabs[tab]))}));
const nav=navGroups.flatMap(group=>group.items);
export default function Admin(){const {user,signOut}=useAuth();const [tab,setTab]=useState('resumen'),[products,setProducts]=useState([]),[categories,setCategories]=useState([]),[promos,setPromos]=useState([]),[promoForm,setPromoForm]=useState(emptyPromo),[editingPromo,setEditingPromo]=useState(null),[answers,setAnswers]=useState([]),[config,setConfig]=useState(defaultSettings),[form,setForm]=useState(empty),[editing,setEditing]=useState(null),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[notice,setNotice]=useState(''),[noticeType,setNoticeType]=useState('success');
 async function load(){setLoading(true);try{const [p,c,r,a,business]=await Promise.all([supabase.from('productos').select('*,categorias(nombre)').order('created_at',{ascending:false}),supabase.from('categorias').select('*').order('orden'),supabase.from('promociones').select('*').order('fecha',{ascending:false}),supabase.from('respuestas_chatbot').select('*').order('clave'),getBusinessSettings()]);const firstError=[p,c,r,a].find(x=>x.error)?.error;if(firstError)throw firstError;const ordered=(p.data||[]).map(product=>({...product,estado:productState(product)})).sort((a,b)=>{if(a.orden==null&&b.orden==null)return 0;if(a.orden==null)return 1;if(b.orden==null)return-1;return a.orden-b.orden});setProducts(ordered);setCategories(c.data||[]);setPromos(r.data||[]);setConfig({...defaultSettings,...business.data});setAnswers(a.data||[])}catch(error){flash(`No fue posible cargar el panel: ${error.message}`,'error')}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);const flash=(message,type='success')=>{setNotice(message);setNoticeType(type);setTimeout(()=>setNotice(''),3500)};
 async function saveProduct(e){e.preventDefault();setBusy(true);const payload={...form,precio:Number(form.precio),orden:Number(form.orden)||0,etiqueta:form.etiqueta||null,disponible:form.estado==='disponible'};const q=editing?supabase.from('productos').update(payload).eq('id',editing):supabase.from('productos').insert(payload);const {error}=await q;setBusy(false);if(error)return flash(`No fue posible guardar el producto: ${error.message}`,'error');setForm(empty);setEditing(null);await load();flash('Producto guardado correctamente')}
 function edit(p){const estado=p.estado||(p.disponible===false?'agotado':'disponible');setForm({nombre:p.nombre,descripcion:p.descripcion||'',precio:p.precio,categoria_id:p.categoria_id||'',imagen:p.imagen||'',disponible:estado==='disponible',estado,etiqueta:p.etiqueta||'',destacado:Boolean(p.destacado),orden:p.orden??0});setEditing(p.id);setTab('productos');scrollTo({top:0,behavior:'smooth'})}
 async function remove(id){if(!confirm('¿Eliminar este producto? Esta acción no se puede deshacer.'))return;setBusy(true);const {error}=await supabase.from('productos').delete().eq('id',id);setBusy(false);if(error)return flash(`No fue posible eliminar el producto: ${error.message}`,'error');await load();flash('Producto eliminado correctamente')}
 async function image(e){const file=e.target.files[0];if(!file)return;setBusy(true);try{setForm({...form,imagen:await uploadImage(file)});flash('Imagen del producto cargada correctamente')}catch(err){flash(`No fue posible cargar la imagen: ${err.message}`,'error')}setBusy(false)}
 async function saveConfig(e){e.preventDefault();setBusy(true);try{setConfig({...defaultSettings,...await saveBusinessSettings(config)});flash('Cambios guardados y publicados')}catch(error){flash(`No fue posible guardar la configuración: ${error.message}`,'error')}finally{setBusy(false)}}
 async function uploadSetting(file,folder,key,returnOnly=false){setBusy(true);try{const url=await uploadImage(file,folder);if(!returnOnly)setConfig(current=>({...current,[key]:url}));flash('Imagen cargada. Guarda los cambios para publicarla.');return url}catch(error){flash(`No fue posible cargar la imagen: ${error.message}`,'error');return ''}finally{setBusy(false)}}
 async function uploadGallery(file,folder,key){setBusy(true);try{const url=await uploadImage(file,folder);setConfig(current=>{let images=[];try{images=JSON.parse(current[key]||'[]')}catch{images=String(current[key]||'').split(',').filter(Boolean)}return {...current,[key]:JSON.stringify([...images,url])}});flash('Imagen cargada. Guarda la galería para publicarla.')}catch(error){flash(`No fue posible cargar la imagen: ${error.message}`,'error')}finally{setBusy(false)}}
 async function addIdentityCategory(nombre){const existing=categories.find(category=>category.nombre.toLowerCase()===nombre.toLowerCase());if(existing){flash('La categoría ya existe y fue agregada a destacados');return existing}setBusy(true);const {data,error}=await supabase.from('categorias').insert({nombre,orden:categories.length+1}).select().single();setBusy(false);if(error){flash(`No fue posible crear la categoría: ${error.message}`,'error');throw error}setCategories(current=>[...current,data]);flash('Categoría venezolana agregada');return data}
 async function togglePromo(p){setBusy(true);const {error}=await supabase.from('promociones').update({activa:!p.activa}).eq('id',p.id);setBusy(false);if(error)return flash(`No fue posible cambiar la promoción: ${error.message}`,'error');await load();flash(p.activa?'Promoción pausada':'Promoción activada')}
 async function savePromo(e){e.preventDefault();if(promoForm.fecha_inicio&&promoForm.fecha_termino&&promoForm.fecha_termino<promoForm.fecha_inicio)return flash('La fecha de término no puede ser anterior al inicio','error');setBusy(true);const payload={...promoForm,fecha_inicio:promoForm.fecha_inicio||null,fecha_termino:promoForm.fecha_termino||null};const query=editingPromo?supabase.from('promociones').update(payload).eq('id',editingPromo):supabase.from('promociones').insert(payload);const {error}=await query;setBusy(false);if(error)return flash(`No fue posible guardar la promoción: ${error.message}`,'error');setPromoForm(emptyPromo);setEditingPromo(null);await load();flash(editingPromo?'Promoción actualizada':'Promoción publicada')}
 function editPromo(p){setEditingPromo(p.id);setPromoForm({titulo:p.titulo,descripcion:p.descripcion||'',imagen:p.imagen||'',activa:p.activa,fecha_inicio:p.fecha_inicio||'',fecha_termino:p.fecha_termino||''});scrollTo({top:0,behavior:'smooth'})}
 async function promoImage(e){const file=e.target.files[0];if(!file)return;setBusy(true);try{setPromoForm({...promoForm,imagen:await uploadImage(file,'promociones')});flash('Imagen de promoción cargada correctamente')}catch(err){flash(`No fue posible cargar la imagen: ${err.message}`,'error')}setBusy(false)}
 async function deletePromo(id){if(!confirm('¿Eliminar esta promoción? Esta acción no se puede deshacer.'))return;setBusy(true);const {error}=await supabase.from('promociones').delete().eq('id',id);setBusy(false);if(error)return flash(`No fue posible eliminar la promoción: ${error.message}`,'error');await load();flash('Promoción eliminada correctamente')}
 async function saveAnswers(){const creating=answers.some(answer=>!answer.id);const clean=answers.map(answer=>({...answer,clave:answer.clave?.trim(),respuesta:answer.respuesta?.trim()}));if(clean.some(answer=>!answer.clave||!answer.respuesta))return flash('La clave y la respuesta son obligatorias','error');const keys=clean.map(answer=>answer.clave);if(new Set(keys).size!==keys.length)return flash('No se permiten claves duplicadas','error');const payload=clean.map(({id,clave,respuesta})=>id?{id,clave,respuesta}:{clave,respuesta});const {error}=await supabase.from('respuestas_chatbot').upsert(payload,{onConflict:'clave'});if(error)return flash(error.code==='23505'?'No se permiten claves duplicadas':`No fue posible guardar las respuestas: ${error.message}`,'error');await load();flash(creating?'Respuesta creada correctamente':'Respuesta actualizada correctamente')}
 async function deleteAnswer(answer,index){if(!confirm('¿Eliminar esta respuesta?'))return;if(answer.id){const {error}=await supabase.from('respuestas_chatbot').delete().eq('id',answer.id);if(error)return flash(`No fue posible eliminar la respuesta: ${error.message}`,'error')}setAnswers(current=>current.filter((_,itemIndex)=>itemIndex!==index));flash('Respuesta eliminada correctamente')}
 async function toggleFeaturedProduct(product){const {error}=await supabase.from('productos').update({destacado:!product.destacado}).eq('id',product.id);if(error)return flash(`No fue posible actualizar el producto: ${error.message}`,'error');setProducts(current=>current.map(item=>item.id===product.id?{...item,destacado:!item.destacado}:item));flash('Productos destacados actualizados')}
 const metrics={total:products.length,disponibles:products.filter(product=>productState(product)==='disponible').length,agotados:products.filter(product=>productState(product)==='agotado').length,ocultos:products.filter(product=>productState(product)==='oculto').length,destacados:products.filter(product=>product.destacado).length,promociones:promos.filter(promo=>promo.activa).length};
 return <main className="admin-shell"><aside className="admin-sidebar"><div className="admin-logo"><span>PC</span><div><b>Pedacito de Cielo</b><small>Administrador</small></div></div><nav>{navGroups.map(group=><div className="admin-nav-group" key={group.label}><span>{group.label}</span>{group.items.map(item=><button key={item[0]} className={tab===item[0]?'active':''} onClick={()=>setTab(item[0])}>{item[1]}</button>)}</div>)}</nav><div className="admin-user"><small>Conectado como</small><b>{user?.email||'Administrador'}</b><button onClick={signOut}>Cerrar sesión</button></div></aside><section className="admin-main" aria-busy={loading||busy}><header><div><small>Panel de control</small><h1>{nav.find(item=>item[0]===tab)?.[1]}</h1></div><Link to="/" target="_blank">Ver sitio ↗</Link></header>{(loading||busy)&&<div className="admin-loading" role="status"><span/>{loading?'Actualizando información del negocio…':'Procesando cambios…'}</div>}{notice&&<div className={`cms-notice ${noticeType==='error'?'error':''}`} role="status">{notice}</div>}
 {tab==='resumen'&&<><section className="dashboard-welcome"><div><span>Resumen del negocio</span><h2>Todo lo importante, de un vistazo</h2><p>Revisa el estado del catálogo y accede rápidamente a las tareas más frecuentes.</p></div><div className="dashboard-actions"><button onClick={()=>setTab('productos')}>Gestionar productos</button><button onClick={()=>setTab('promociones')}>Ver promociones</button></div></section><div className="stats dashboard-stats"><article><span>Total de productos</span><b>{metrics.total}</b><small>Registrados en el catálogo</small></article><article className="metric-available"><span>Disponibles</span><b>{metrics.disponibles}</b><small>Listos para vender</small></article><article className="metric-soldout"><span>Agotados</span><b>{metrics.agotados}</b><small>Visibles sin compra</small></article><article className="metric-hidden"><span>Ocultos</span><b>{metrics.ocultos}</b><small>No visibles públicamente</small></article><article className="metric-featured"><span>Destacados</span><b>{metrics.destacados}</b><small>Favoritos de la casa</small></article><article className="metric-promos"><span>Promociones activas</span><b>{metrics.promociones}</b><small>Publicadas actualmente</small></article></div><section className="admin-card"><div className="card-title"><div><h2>Vista rápida de productos</h2><p>Los primeros productos según el orden comercial configurado.</p></div><button onClick={()=>setTab('productos')}>Gestionar productos →</button></div>{products.length?<ProductTable products={products.slice(0,5)} edit={edit} remove={remove}/>:<div className="empty-state">Aún no hay productos registrados.</div>}</section></>}
 {tab==='analitica'&&<AnalyticsPanel/>}
 {tab==='crm'&&<CrmPanel/>}
 {tab==='productos'&&<><section className="admin-card product-form"><div className="card-title"><div><h2>{editing?'Editar producto':'Nuevo producto'}</h2><p>Controla su visibilidad, prioridad y presentación comercial.</p></div>{editing&&<button onClick={()=>{setEditing(null);setForm(empty)}}>Cancelar</button>}</div><form onSubmit={saveProduct} className="cms-form"><label>Nombre<input required value={form.nombre} onChange={e=>setForm({...form,nombre:e.target.value})}/></label><label>Precio CLP<input required type="number" value={form.precio} onChange={e=>setForm({...form,precio:e.target.value})}/></label><label className="wide">Descripción<textarea value={form.descripcion} onChange={e=>setForm({...form,descripcion:e.target.value})}/></label><label>Categoría<select required value={form.categoria_id} onChange={e=>setForm({...form,categoria_id:e.target.value})}><option value="">Seleccionar</option>{categories.map(c=><option value={c.id} key={c.id}>{c.nombre}</option>)}</select></label><label>Imagen<input type="file" accept="image/*" onChange={image}/></label>{form.imagen&&<img className="image-preview" src={form.imagen} alt="Vista previa"/>}<label>Estado<select value={form.estado} onChange={e=>setForm({...form,estado:e.target.value,disponible:e.target.value==='disponible'})}><option value="disponible">Disponible</option><option value="agotado">Agotado</option><option value="oculto">Oculto</option></select></label><label>Etiqueta comercial<select value={form.etiqueta} onChange={e=>setForm({...form,etiqueta:e.target.value})}><option value="">Sin etiqueta</option>{productLabels.map(label=><option key={label} value={label}>{label}</option>)}</select></label><label>Orden de aparición<input type="number" min="0" value={form.orden} onChange={e=>setForm({...form,orden:e.target.value})}/></label><label className="check"><input type="checkbox" checked={form.destacado} onChange={e=>setForm({...form,destacado:e.target.checked})}/> Mostrar en Favoritos de Pedacito de Cielo</label><button className="cms-primary" disabled={busy}>{busy?'Guardando…':'Guardar producto'}</button></form></section><section className="admin-card"><div className="card-title"><div><h2>Todos los productos</h2><p>{products.length} elementos en el catálogo, ordenados por prioridad.</p></div></div><ProductTable products={products} edit={edit} remove={remove}/></section></>}
 {tab==='promociones'&&<><section className="admin-card"><div className="card-title"><div><h2>{editingPromo?'Editar promoción':'Nueva promoción'}</h2><p>Prepara campañas y define opcionalmente su periodo de vigencia.</p></div>{editingPromo&&<button onClick={()=>{setEditingPromo(null);setPromoForm(emptyPromo)}}>Cancelar</button>}</div><form className="cms-form" onSubmit={savePromo}><label>Nombre de la promoción<input required value={promoForm.titulo} onChange={e=>setPromoForm({...promoForm,titulo:e.target.value})}/></label><label>Imagen<input type="file" accept="image/*" onChange={promoImage}/></label><label className="wide">Descripción<textarea value={promoForm.descripcion} onChange={e=>setPromoForm({...promoForm,descripcion:e.target.value})}/></label><label>Fecha de inicio (opcional)<input type="date" value={promoForm.fecha_inicio} onChange={e=>setPromoForm({...promoForm,fecha_inicio:e.target.value})}/></label><label>Fecha de término (opcional)<input type="date" min={promoForm.fecha_inicio||undefined} value={promoForm.fecha_termino} onChange={e=>setPromoForm({...promoForm,fecha_termino:e.target.value})}/></label><label className="check"><input type="checkbox" checked={promoForm.activa} onChange={e=>setPromoForm({...promoForm,activa:e.target.checked})}/> Promoción activa</label>{promoForm.imagen&&<img className="image-preview" src={promoForm.imagen} alt="Vista previa de promoción"/>}<button className="cms-primary" disabled={busy}>{editingPromo?'Guardar promoción':'Publicar promoción'}</button></form></section><section className="admin-card"><div className="card-title"><div><h2>Promociones</h2><p>Activa, pausa, edita o elimina campañas.</p></div></div><div className="promo-list">{promos.map(p=><article key={p.id}><img src={p.imagen||'/images/productos/torta-chocolate.jpg'} alt=""/><div><small>{p.activa?'Publicada':'Pausada'}{p.fecha_inicio||p.fecha_termino?` · ${p.fecha_inicio||'Sin inicio'} — ${p.fecha_termino||'Sin término'}`:''}</small><h3>{p.titulo}</h3><p>{p.descripcion}</p></div><div><button onClick={()=>editPromo(p)}>Editar</button><button onClick={()=>togglePromo(p)}>{p.activa?'Pausar':'Activar'}</button><button onClick={()=>deletePromo(p.id)}>Eliminar</button></div></article>)}{!promos.length&&<div className="empty-state">Aún no hay promociones.</div>}</div></section></>}
 {['pagina','nosotros','diseno','contacto','chatbot'].includes(tab)&&<CmsSectionEditor mode={tab} config={config} setConfig={setConfig} answers={answers} setAnswers={setAnswers} onSave={saveConfig} onSaveAnswers={saveAnswers} onDeleteAnswer={deleteAnswer} onNotify={flash} onUpload={uploadSetting} busy={busy}/>}
 {tab==='novedades'&&<NewsSettings config={config} setConfig={setConfig} onSave={saveConfig} onNotify={flash} busy={busy}/>}
 {tab==='identidad'&&<IdentitySettings config={config} setConfig={setConfig} categories={categories} products={products} answers={answers} setAnswers={setAnswers} onSave={saveConfig} onSaveAnswers={saveAnswers} onAddCategory={addIdentityCategory} onToggleFeatured={toggleFeaturedProduct} onUploadMain={uploadSetting} onUploadGallery={uploadGallery} busy={busy}/>}
 {tab==='cuenta'&&<AccountSettings/>}
 </section></main>}
function ProductTable({products,edit,remove}){return <div className="cms-table">{products.map(p=>{const estado=p.estado||(p.disponible===false?'agotado':'disponible');return <article key={p.id}><img src={p.imagen||'/images/productos/marraqueta.jpg'} alt=""/><div><b>{p.nombre}</b><small>{p.categorias?.nombre||'Sin categoría'} · Orden {p.orden??'actual'}</small><div className="product-admin-meta">{p.etiqueta&&<span>{p.etiqueta}</span>}{p.destacado&&<span>★ Destacado</span>}</div></div><strong>${Number(p.precio).toLocaleString('es-CL')}</strong><span className={`status ${estado==='disponible'?'on':estado==='oculto'?'hidden':''}`}>{estado==='disponible'?'Disponible':estado==='agotado'?'Agotado':'Oculto'}</span><div className="row-actions"><button onClick={()=>edit(p)}>Editar</button><button onClick={()=>remove(p.id)}>Eliminar</button></div></article>})}</div>}
