import { useMemo, useState } from 'react';
import '../styles/venezuelan-gallery.css';

export default function BakerySite({productos=[],negocio,contenido={},responses,promociones=[],loading=false}){
 const [menu,setMenu]=useState(false),[category,setCategory]=useState('Todos'),[chat,setChat]=useState(false);
 const [answer,setAnswer]=useState('');
 const welcomeMessage=`¡Hola! Soy ${negocio.chatbot_nombre||'Cielito'} ☁️\n\nEstoy aquí para ayudarte a conocer nuestros productos venezolanos, horarios y pedidos.\n\n¿En qué puedo ayudarte?`;
 const categories=['Todos',...new Set(productos.map(p=>p.categoria))];
 const wa=(message)=>`https://wa.me/${negocio.whatsapp}?text=${encodeURIComponent(message)}`;
 const filtered=useMemo(()=>category==='Todos'?productos:productos.filter(p=>p.categoria===category),[category,productos]);
 const featured=productos.filter(p=>p.destacado);
 const flavorCategories=(negocio.categorias_destacadas||'Arepas,Tequeños,Cachapas,Empanadas venezolanas,Pan de jamón,Golfeados').split(',').map(item=>item.trim()).filter(Boolean);
 const parseGallery=(value)=>{if(Array.isArray(value))return value;try{const parsed=JSON.parse(value||'[]');return Array.isArray(parsed)?parsed:[]}catch{return String(value||'').split(',').map(item=>item.trim()).filter(Boolean)}};
 const identityGallery=[...parseGallery(negocio.galeria_productos),...parseGallery(negocio.galeria_local),...parseGallery(negocio.galeria_promociones)].slice(0,6);
 const nav=contenido.navegacion||{},ui=contenido.interfaz||{},hero=contenido.hero||{},featuredCopy=contenido.destacados||{},daily=contenido.recomendacion||{},promotionCopy=contenido.promociones||{},venezuela=contenido.venezuela||{},catalogCopy=contenido.catalogo||{},about=contenido.nosotros||{},testimonials=contenido.testimonios||{},contact=contenido.contacto||{},footerCopy=contenido.footer||{},chatCopy=contenido.chatbot||{};
 const siteStyle={'--cafe':negocio.color_principal||'#173a5e','--naranja':negocio.color_secundario||'#c94a3a','--crema':negocio.color_fondo||'#fff8e8','--brown':negocio.color_principal||'#173a5e','--orange':negocio.color_secundario||'#c94a3a','--paper':negocio.color_fondo||'#fff8e8','--maiz':negocio.color_destacado||'#e7b83f'};
 const socialLinks=[['Instagram',negocio.redes?.instagram],['Facebook',negocio.redes?.facebook],['TikTok',negocio.redes?.tiktok]].filter(([,url])=>url&&url!=='#');
 const topbar={
  horneado:negocio.topbar_horneado?.trim()||'Horneamos durante todo el día',
  retiro:ui.retiro?.trim()||'Retiro en tienda',
  direccion:negocio.direccion?.trim()||'Quillota 849, Viña del Mar',
 };
 if(loading)return <div className="site-loading">Preparando productos frescos…</div>;
 return <main style={siteStyle}>
  <div className="topbar"><span className="topbar-text">{topbar.horneado}</span><span aria-hidden="true">•</span><span className="topbar-text">{topbar.retiro}</span><span aria-hidden="true">•</span><span className="topbar-text">{topbar.direccion}</span></div>
  <header className="nav-wrap"><nav className="nav container">
   <a className="brand" href="#inicio">{negocio.logo?<img className="brand-logo" src={negocio.logo} alt={`Logo ${negocio.nombre}`}/>:<span className="brand-mark">PC</span>}<span><b>{negocio.nombre||'Pedacito de Cielo'}</b><small>{footerCopy.descriptor}</small></span></a>
   <button className="menu-btn" onClick={()=>setMenu(!menu)} aria-label="Abrir menú">{menu?'✕':'☰'}</button>
   <div className={`nav-links ${menu?'open':''}`}><a href="#inicio">{nav.inicio}</a><a href="#sabores">{nav.sabores}</a><a href="#catalogo">{nav.catalogo}</a><a href="#nosotros">{nav.nosotros}</a><a href="#contacto">{nav.contacto}</a><a className="nav-order" href={wa('Hola Pedacito de Cielo, quisiera hacer un pedido.')} target="_blank">{nav.pedido} ↗</a></div>
  </nav></header>
  <section id="inicio" className="hero"><div className="container hero-grid"><div className="hero-copy">
   <div className="eyebrow"><span/> {hero.eyebrow}</div><h1>{hero.titulo||negocio.frase_marca} <em>{hero.destacado||negocio.hero_destacado}</em></h1><p>{hero.texto||negocio.mensaje_bienvenida}</p>
   <div className="hero-actions"><a className="btn primary" href="#catalogo">{hero.boton_catalogo} ↓</a><a className="btn text-btn" href={wa('Hola Pedacito de Cielo, quisiera hacer un pedido.')} target="_blank">{hero.boton_whatsapp} ↗</a></div>
   <div className="trust-row"><div className="avatars"><i>♥</i><i>PC</i><i>★</i></div><p><b>{hero.confianza_titulo}</b><span>{hero.confianza_texto}</span></p></div>
  </div><div className="hero-visual"><div className="hero-image" style={negocio.imagen_portada?{backgroundImage:`url(${negocio.imagen_portada})`}:undefined}/><div className="fresh-card"><span>◉</span><div><b>{hero.tarjeta_titulo}</b><small>{hero.tarjeta_texto}</small></div></div><div className="since-badge"><b>{ui.hecho}</b><span>{ui.con_carino}</span></div></div></div>
  <div className="container benefit-strip">{(contenido.beneficios||[]).map(x=><div key={x.titulo}><span>{x.icono}</span><p><b>{x.titulo}</b><small>{x.texto}</small></p></div>)}</div></section>

  <section className="featured section container"><div className="section-head"><div><span className="kicker">{featuredCopy.kicker}</span><h2>{featuredCopy.titulo}</h2></div><a href="#catalogo">{featuredCopy.enlace} →</a></div><div className="featured-grid">{featured.slice(0,3).map((p,i)=><article className={`feature-card f${i}`} key={p.id}><img src={p.imagen} alt={p.nombre}/><div className="feature-overlay"><span>{p.categoria}</span><h3>{p.nombre}</h3><p>{p.descripcion}</p><div><b>{p.precio}</b><a href={wa(`Hola Pedacito de Cielo, quisiera consultar por ${p.nombre}.`)} target="_blank">{ui.pedir} ↗</a></div></div></article>)}</div></section>

  <section className="daily"><div className="container daily-grid"><div className="daily-photo" style={daily.imagen?{backgroundImage:`linear-gradient(90deg,transparent 75%,var(--azul)),url(${daily.imagen})`}:undefined}/><div className="daily-copy"><span className="kicker light">{daily.kicker}</span><h2>{daily.titulo}</h2><p>{daily.texto}</p><a className="btn cream" href={wa('Hola Pedacito de Cielo, quisiera conocer la recomendación venezolana de hoy.')} target="_blank">{daily.boton} ↗</a></div></div></section>

  <section id="sabores" className="venezuela-story section"><div className="container venezuela-grid"><div className="venezuela-copy"><span className="kicker">{venezuela.kicker}</span><h2>{venezuela.titulo}</h2><p>{venezuela.descripcion||negocio.descripcion_cultural}</p><p>{venezuela.texto_secundario||negocio.historia_venezolana}</p><a className="text-link" href="#catalogo">{venezuela.boton} →</a></div><div className="flavor-panel"><span className="corn-mark">✦</span><small>{venezuela.panel_titulo}</small><div className="flavor-tags">{flavorCategories.map(item=><span key={item}>{item}</span>)}</div><p>{venezuela.panel_texto}</p></div></div></section>
  {identityGallery.length>0&&<section className="identity-public-gallery container" aria-label="Galería venezolana">{identityGallery.map((url,index)=><img key={`${url}-${index}`} src={url} alt={`Galería de Pedacito de Cielo ${index+1}`}/>)}</section>}

  {promociones.length>0&&<section className="promotions section container"><div className="section-head"><div><span className="kicker">{promotionCopy.kicker}</span><h2>{promotionCopy.titulo}</h2></div></div><div className="promo-public-grid">{promociones.map(p=><article key={p.id}>{p.imagen&&<img src={p.imagen} alt={p.titulo}/>}<div><h3>{p.titulo}</h3><p>{p.descripcion}</p><a href={wa(`Hola Pedacito de Cielo, quisiera consultar por la promoción ${p.titulo}.`)} target="_blank">{promotionCopy.boton} ↗</a></div></article>)}</div></section>}

  <section id="catalogo" className="catalog section container"><div className="center-head"><span className="kicker">{catalogCopy.kicker}</span><h2>{catalogCopy.titulo}</h2><p>{catalogCopy.descripcion}</p></div><div className="filters">{categories.map(c=><button key={c} className={category===c?'active':''} onClick={()=>setCategory(c)}>{c}</button>)}</div><div className="product-grid">{filtered.map(p=><article className="product-card" key={p.id}><div className="product-img"><img src={p.imagen} alt={p.nombre}/><span className={p.disponible?'available':'unavailable'}>{p.disponible?ui.disponible:ui.agotado}</span></div><div className="product-body"><small>{p.categoria}</small><h3>{p.nombre}</h3><p>{p.descripcion}</p><div className="product-bottom"><b>{p.precio}</b>{p.disponible?<a aria-label={`${ui.pedir} ${p.nombre}`} href={wa(`Hola Pedacito de Cielo, quisiera consultar por este producto: ${p.nombre}.`)} target="_blank">＋</a>:<span>—</span>}</div></div></article>)}</div></section>

  <section id="nosotros" className="story section"><div className="container story-grid"><div className="story-copy"><span className="kicker">{about.kicker}</span><h2>{about.titulo}</h2><p>{negocio.historia||about.historia}</p><p>{about.texto_secundario}</p><div className="signature">{about.firma}</div></div><div className="story-images"><img src={about.imagen} alt="Historia de Pedacito de Cielo"/><div className="quote"><b>“</b><p>{about.cita}</p></div></div></div></section>

  <section className="testimonials section container"><div className="center-head"><span className="kicker">{testimonials.kicker}</span><h2>{testimonials.titulo}</h2></div><div className="testimonial-grid">{(testimonials.items||[]).map(item=><article key={item.nombre}><div className="stars">★★★★★</div><p>“{item.texto}”</p><b>{item.nombre}</b><small>{item.detalle}</small></article>)}</div></section>

  <section id="contacto" className="visit"><div className="container visit-grid"><div className="visit-info"><span className="kicker light">{contact.kicker}</span><h2>{contact.titulo}</h2><div className="info-row"><span>⌖</span><div><small>{contact.direccion_etiqueta}</small><b>{negocio.direccion}</b><a href={`https://maps.google.com/?q=${encodeURIComponent(negocio.direccion)}`} target="_blank">{contact.mapa_boton} →</a></div></div><div className="info-row"><span>◷</span><div><small>{contact.horarios_etiqueta}</small><b>{negocio.horarios.semana}</b><b>{negocio.horarios.domingo}</b></div></div><a className="btn cream" href={wa(`Hola ${negocio.nombre||'Pedacito de Cielo'}, quisiera hacer una consulta.`)} target="_blank">{contact.whatsapp_boton} ↗</a></div><iframe title="Mapa de ubicación" src={contact.mapa_url||`https://www.google.com/maps?q=${encodeURIComponent(negocio.direccion)}&output=embed`} loading="lazy"/></div></section>

  <footer><div className="container footer-grid"><div className="brand footer-brand">{negocio.logo?<img className="brand-logo" src={negocio.logo} alt=""/>:<span className="brand-mark">PC</span>}<span><b>{negocio.nombre||'Pedacito de Cielo'}</b><small>{footerCopy.descriptor}</small></span></div><p>{footerCopy.texto||negocio.descripcion}</p><div className="footer-links"><a href="#sabores">{nav.sabores}</a><a href="#catalogo">{nav.catalogo}</a><a href="#nosotros">{nav.nosotros}</a><a href="#contacto">{nav.contacto}</a>{socialLinks.map(([label,url])=><a key={label} href={url} target="_blank" rel="noopener noreferrer">{label} ↗</a>)}</div></div><div className="container copyright">© 2026 {negocio.nombre||'Pedacito de Cielo'} <span>{negocio.direccion}</span></div></footer>
  <button className="chat-fab" onClick={()=>setChat(!chat)} aria-label="Abrir asistente">{chat?'✕':'☁'}<span>{chatCopy.boton}</span></button>
  {chat&&<aside className="chatbox"><header><div><span>☁</span><p><b>{negocio.chatbot_nombre}</b><small>{ui.asistente_de} {negocio.nombre}</small></p></div><button onClick={()=>setChat(false)}>✕</button></header><div className="chat-body"><div className="bubble">{answer||welcomeMessage}</div><p className="chat-label">{chatCopy.preguntas_titulo}</p><div className="quick">{(chatCopy.preguntas||[]).map(question=><button key={question.key} onClick={()=>setAnswer(responses[String(question.key||'').trim().toLowerCase()]||'Escríbenos por WhatsApp para ayudarte.')}>{question.label}</button>)}</div></div><a className="chat-wa" href={wa(`Hola ${negocio.nombre||'Pedacito de Cielo'}, necesito ayuda con mi pedido.`)} target="_blank">{chatCopy.whatsapp_boton} ↗</a></aside>}
 </main>
}

