import { useMemo, useState } from 'react';
import '../styles/venezuelan-gallery.css';
import { MEASUREMENT_EVENTS, trackEvent } from '../utils/measurement.js';
import { brandingConfig, businessConfig, moduleConfig } from '../config/siteConfig.js';

const optimizedImage=(src)=>typeof src==='string'&&src.startsWith('/images/')&&/\.jpe?g(?:[?#].*)?$/i.test(src)?src.replace(/\.jpe?g(?=([?#]|$))/i,'.webp'):src;

export default function BakerySite({productos=[],negocio,contenido={},responses={},promociones=[],loading=false}){
 const [menu,setMenu]=useState(false),[category,setCategory]=useState('Todos'),[chat,setChat]=useState(false);
 const [answer,setAnswer]=useState(''),[answerKey,setAnswerKey]=useState('');
 const businessName=negocio.nombre?.trim()||brandingConfig.name;
 const assistantName=negocio.chatbot_nombre?.trim()||businessConfig.chatbot_nombre;
 const welcomeMessage=negocio.chatbot_mensaje?.trim()||`¡Hola! Soy ${assistantName} ☁️, tu asistente de ${businessName}. Estoy aquí para ayudarte a descubrir nuestros productos.`;
 const visibleProducts=useMemo(()=>productos.filter(product=>product.estado!=='oculto'),[productos]);
 const categories=['Todos',...new Set(visibleProducts.map(p=>p.categoria))];
 const wa=(message)=>`https://wa.me/${negocio.whatsapp}?text=${encodeURIComponent(message)}`;
 const filtered=useMemo(()=>category==='Todos'?visibleProducts:visibleProducts.filter(p=>p.categoria===category),[category,visibleProducts]);
 const featured=visibleProducts.filter(p=>p.destacado);
 const allowedProductLabels=new Set(['Más vendido','Favorito','Recomendado','Nuevo']);
 const getProductLabels=(product)=>[...(Array.isArray(product.etiquetas)?product.etiquetas:[]),product.etiqueta].filter(label=>allowedProductLabels.has(label));
 const flavorCategories=(negocio.categorias_destacadas||businessConfig.categorias_destacadas||'').split(',').map(item=>item.trim()).filter(Boolean);
 const parseGallery=(value)=>{if(Array.isArray(value))return value;try{const parsed=JSON.parse(value||'[]');return Array.isArray(parsed)?parsed:[]}catch{return String(value||'').split(',').map(item=>item.trim()).filter(Boolean)}};
 const identityGallery=[...parseGallery(negocio.galeria_productos),...parseGallery(negocio.galeria_local),...parseGallery(negocio.galeria_promociones)].slice(0,6);
 const nav=contenido.navegacion||{},ui=contenido.interfaz||{},hero=contenido.hero||{},valueCopy=contenido.propuesta_valor||{},brandValues=contenido.representa||{},featuredCopy=contenido.destacados||{},daily=contenido.recomendacion||{},promotionCopy=contenido.promociones||{},venezuela=contenido.venezuela||{},catalogCopy=contenido.catalogo||{},about=contenido.nosotros||{},instagramCopy=contenido.instagram||{},testimonials=contenido.testimonios||{},communityCopy=contenido.comunidad||{},newsCopy=contenido.novedades||{},finalCta=contenido.cta_final||{},contact=contenido.contacto||{},footerCopy=contenido.footer||{},chatCopy=contenido.chatbot||{};
 const siteStyle={'--cafe':negocio.color_principal||brandingConfig.colors.primary,'--naranja':negocio.color_secundario||brandingConfig.colors.secondary,'--crema':negocio.color_fondo||brandingConfig.colors.background,'--brown':negocio.color_principal||brandingConfig.colors.primary,'--orange':negocio.color_secundario||brandingConfig.colors.secondary,'--paper':negocio.color_fondo||brandingConfig.colors.background,'--maiz':negocio.color_destacado||brandingConfig.colors.accent};
 const socialLinks=[['Instagram',negocio.redes?.instagram],['Facebook',negocio.redes?.facebook],['TikTok',negocio.redes?.tiktok]].filter(([,url])=>url&&url!=='#');
 const topbar={
  horneado:negocio.topbar_horneado?.trim()||'Horneamos durante todo el día',
  retiro:ui.retiro?.trim()||'Retiro en tienda',
  direccion:negocio.direccion?.trim()||businessConfig.direccion,
 };
 const quickQuestions=chatCopy.opciones_iniciales||chatCopy.preguntas||[];
 const availableProductNames=visibleProducts.filter(product=>product.estado==='disponible'||(!product.estado&&product.disponible)).slice(0,3).map(product=>product.nombre);
 const chooseChatOption=(question)=>{const key=String(question.key||'').trim().toLowerCase();const productAnswer=availableProductNames.length?`Para comenzar, puedes conocer ${availableProductNames.join(', ')}. Revisa el catálogo para ver todos los productos, precios y disponibilidad.`:responses.productos;trackEvent(MEASUREMENT_EVENTS.CHATBOT_QUESTION,{questionKey:key,questionLabel:question.label||key});setAnswerKey(key);setAnswer(key==='productos'?productAnswer:(responses[key]||'Cuéntanos qué necesitas por WhatsApp y te ayudaremos personalmente.'));};
 const mapsUrl=`https://maps.google.com/?q=${encodeURIComponent(negocio.direccion)}`;
 const chatActions={productos:[['Ver catálogo','#catalogo',true],['Consultar por WhatsApp',wa(`Hola ${businessName}, quisiera conocer los productos disponibles.`)]],direccion:[['Abrir en Google Maps',mapsUrl],['Consultar por WhatsApp',wa(`Hola ${businessName}, necesito ayuda para llegar al local.`)]],horarios:[['Hacer un pedido',wa(`Hola ${businessName}, quisiera consultar disponibilidad y hacer un pedido.`)]],compra:[['Hacer pedido por WhatsApp',wa(`Hola ${businessName}, quisiera hacer un pedido.`)]],contacto:[['Escribir por WhatsApp',wa(`Hola ${businessName}, quisiera hacer una consulta.`)],['Visitar Instagram',negocio.redes?.instagram]]};
 const activeChatActions=answerKey?(chatActions[answerKey]||[['Continuar por WhatsApp',wa(`Hola ${businessName}, necesito ayuda con mi pedido.`)]]):[];
 const moduleClasses=Object.entries(moduleConfig).filter(([,enabled])=>enabled===false).map(([name])=>`module-off-${name}`).join(' ');
 const trackPublicAction=(event)=>{const link=event.target.closest('a');if(!link)return;const href=link.getAttribute('href')||'';const location=link.closest('aside')?'chatbot':link.closest('#catalogo')?'catalogo':link.closest('header')?'navegacion':'pagina';const productName=link.dataset.product||'';if(href.startsWith('https://wa.me/'))trackEvent(MEASUREMENT_EVENTS.WHATSAPP_CLICK,{location,...(productName?{productName}:{})});if(href==='#catalogo')trackEvent(MEASUREMENT_EVENTS.CATALOG_CLICK,{location});};
 if(loading)return <div className="site-loading">Preparando productos frescos…</div>;
 return <main className={moduleClasses} style={siteStyle} onClick={trackPublicAction}>
  <div className="topbar"><span className="topbar-text">{topbar.horneado}</span><span aria-hidden="true">•</span><span className="topbar-text">{topbar.retiro}</span><span aria-hidden="true">•</span><span className="topbar-text">{topbar.direccion}</span></div>
  <header className="nav-wrap"><nav className="nav container">
   <a className="brand" href="#inicio">{negocio.logo?<img className="brand-logo" src={optimizedImage(negocio.logo)} alt={`Logo ${businessName}`} decoding="async"/>:<span className="brand-mark">{brandingConfig.initials}</span>}<span><b>{businessName}</b><small>{footerCopy.descriptor}</small></span></a>
   <button type="button" className="menu-btn" onClick={()=>setMenu(!menu)} aria-label={menu?'Cerrar menú':'Abrir menú'} aria-expanded={menu} aria-controls="public-navigation">{menu?'✕':'☰'}</button>
   <div id="public-navigation" className={`nav-links ${menu?'open':''}`}><a href="#inicio">{nav.inicio}</a><a href="#sabores">{nav.sabores}</a><a href="#catalogo">{nav.catalogo}</a><a href="#nosotros">{nav.nosotros}</a><a href="#contacto">{nav.contacto}</a><a className="nav-order" href={wa(`Hola ${businessName}, quisiera hacer un pedido.`)} target="_blank" rel="noopener noreferrer">{nav.pedido} ↗</a></div>
  </nav></header>
  <section id="inicio" className="hero"><div className="container hero-grid"><div className="hero-copy">
   <div className="eyebrow"><span/> {hero.eyebrow}</div><h1>{hero.titulo||negocio.frase_marca} <em>{hero.destacado||negocio.hero_destacado}</em></h1><p>{hero.texto||negocio.mensaje_bienvenida}</p>
   <div className="hero-actions"><a className="btn primary" href="#catalogo">{hero.boton_catalogo} ↓</a><a className="btn text-btn" href={wa(`Hola ${businessName}, quisiera hacer un pedido.`)} target="_blank">{hero.boton_whatsapp} ↗</a></div>
   <div className="trust-row"><div className="avatars"><i>♥</i><i>PC</i><i>★</i></div><p><b>{hero.confianza_titulo}</b><span>{hero.confianza_texto}</span></p></div>
  </div><div className="hero-visual"><div className="hero-image" style={negocio.imagen_portada?{backgroundImage:`url(${optimizedImage(negocio.imagen_portada)})`}:undefined}/><div className="fresh-card"><span>◉</span><div><b>{hero.tarjeta_titulo}</b><small>{hero.tarjeta_texto}</small></div></div><div className="since-badge"><b>{ui.hecho}</b><span>{ui.con_carino}</span></div></div></div></section>

  <section className="value-proposition" aria-labelledby="value-proposition-title"><div className="container"><div className="value-heading"><span className="kicker">{valueCopy.kicker}</span><h2 id="value-proposition-title">{valueCopy.titulo}</h2></div><div className="benefit-strip">{(valueCopy.items||[]).map(x=><article key={x.titulo}><span>{x.icono}</span><div><h3>{x.titulo}</h3><p>{x.texto}</p></div></article>)}</div></div></section>

  <section id="nosotros" className="story section"><div className="container story-grid"><div className="story-copy"><span className="kicker">{about.kicker}</span><h2>{about.titulo}</h2><p>{negocio.historia||about.historia}</p>{about.texto_secundario&&<p>{about.texto_secundario}</p>}{about.firma&&<div className="signature">{about.firma}</div>}</div><div className="story-images">{about.imagen?<img src={optimizedImage(about.imagen)} alt={businessName} loading="lazy" decoding="async"/>:<div className="story-image-placeholder"><span>Imagen del negocio</span><small>Agrega una fotografía real desde el editor de contenido</small></div>}{about.cita&&<div className="quote"><b>“</b><p>{about.cita}</p></div>}</div></div></section>

  <section className="brand-values section"><div className="container"><div className="center-head"><span className="kicker">{brandValues.kicker}</span><h2>{brandValues.titulo}</h2></div><div className="brand-values-grid">{(brandValues.items||[]).map(item=><article key={item.titulo}><span>{item.icono}</span><h3>{item.titulo}</h3><p>{item.texto}</p></article>)}</div></div></section>

  {featured.length>0&&<section className="featured section container"><div className="section-head"><div><span className="kicker">{featuredCopy.kicker}</span><h2>{featuredCopy.titulo}</h2></div><a href="#catalogo">{featuredCopy.enlace} →</a></div><div className="featured-grid">{featured.slice(0,3).map((p,i)=><article className={`feature-card f${i}`} key={p.id}><img src={optimizedImage(p.imagen)} alt={p.nombre} loading="lazy" decoding="async"/><div className="feature-overlay"><span>{p.categoria}</span><h3>{p.nombre}</h3><p>{p.descripcion}</p><div><b>{p.precio}</b><a href={wa(`Hola ${businessName}, quisiera consultar por ${p.nombre}.`)} data-product={p.nombre} target="_blank">{ui.pedir} ↗</a></div></div></article>)}</div></section>}

  <section className="daily"><div className="container daily-grid"><div className="daily-photo" style={daily.imagen?{backgroundImage:`linear-gradient(90deg,transparent 75%,var(--azul)),url(${optimizedImage(daily.imagen)})`}:undefined}/><div className="daily-copy"><span className="kicker light">{daily.kicker}</span><h2>{daily.titulo}</h2><p>{daily.texto}</p><a className="btn cream" href={wa(`Hola ${businessName}, quisiera conocer la recomendación de hoy.`)} target="_blank">{daily.boton} ↗</a></div></div></section>

  <section id="sabores" className="venezuela-story section"><div className="container venezuela-grid"><div className="venezuela-copy"><span className="kicker">{venezuela.kicker}</span><h2>{venezuela.titulo}</h2><p>{venezuela.descripcion||negocio.descripcion_cultural}</p><p>{venezuela.texto_secundario||negocio.historia_venezolana}</p><a className="text-link" href="#catalogo">{venezuela.boton} →</a></div><div className="flavor-panel"><span className="corn-mark">✦</span><small>{venezuela.panel_titulo}</small><div className="flavor-tags">{flavorCategories.map(item=><span key={item}>{item}</span>)}</div><p>{venezuela.panel_texto}</p></div></div></section>
  {identityGallery.length>0&&<section className="identity-public-gallery container" aria-label="Galería del negocio">{identityGallery.map((url,index)=><img key={`${url}-${index}`} src={optimizedImage(url)} alt={`Galería de ${businessName} ${index+1}`} loading="lazy" decoding="async"/>)}</section>}

  {promociones.length>0&&<section className="promotions section container"><div className="section-head"><div><span className="kicker">{promotionCopy.kicker}</span><h2>{promotionCopy.titulo}</h2></div></div><div className="promo-public-grid">{promociones.map(p=><article key={p.id}>{p.imagen&&<img src={optimizedImage(p.imagen)} alt={p.titulo} loading="lazy" decoding="async"/>}<div><h3>{p.titulo}</h3><p>{p.descripcion}</p><a href={wa(`Hola ${businessName}, quisiera consultar por la promoción ${p.titulo}.`)} target="_blank">{promotionCopy.boton} ↗</a></div></article>)}</div></section>}

  <section id="catalogo" className="catalog section container"><div className="center-head catalog-heading"><span className="kicker">{catalogCopy.kicker}</span><h2>{catalogCopy.titulo}</h2><p>{catalogCopy.descripcion}</p></div><div className="filters" aria-label="Filtrar productos por categoría">{categories.map(c=><button type="button" key={c} className={category===c?'active':''} aria-pressed={category===c} onClick={()=>setCategory(c)}>{c}</button>)}</div><div className="product-grid">{filtered.map(p=>{const labels=getProductLabels(p);const action=/cotizar/i.test(String(p.precio))?'Consultar producto':'Pedir por WhatsApp';return <article className="product-card" key={p.id}><div className="product-img"><img src={optimizedImage(p.imagen)} alt={p.nombre} loading="lazy" decoding="async"/><span className={p.disponible?'available':'unavailable'}>{p.disponible?ui.disponible:ui.agotado}</span>{labels.length>0&&<div className="product-commercial-tags">{labels.map(label=><span key={label}>{label}</span>)}</div>}</div><div className="product-body"><small>{p.categoria}</small><h3>{p.nombre}</h3><p className="product-description">{p.descripcion||''}</p><div className="product-bottom"><b>{p.precio}</b></div>{p.disponible?<a className="product-cta" aria-label={`${action}: ${p.nombre}`} href={wa(`Hola ${businessName}, quisiera consultar por este producto: ${p.nombre}.`)} data-product={p.nombre} target="_blank" rel="noopener noreferrer">{action}<span aria-hidden="true">↗</span></a>:<span className="product-cta disabled">Agotado por hoy</span>}</div></article>})}</div></section>

  <section className="testimonials section container"><div className="center-head"><span className="kicker">{testimonials.kicker}</span><h2>{testimonials.titulo}</h2></div>{(testimonials.items||[]).length>0?<div className="testimonial-grid">{testimonials.items.map(item=><article key={`${item.nombre}-${item.texto}`}><div className="stars">★★★★★</div><p>“{item.texto}”</p><b>{item.nombre}</b><small>{item.detalle}</small></article>)}</div>:<div className="testimonial-empty"><span>☆</span><h3>{testimonials.vacio_titulo}</h3><p>{testimonials.vacio_texto}</p></div>}</section>

  {negocio.redes?.instagram&&<section className="instagram-invite"><div className="container instagram-invite-grid"><div><span className="kicker light">{instagramCopy.kicker}</span><h2>{instagramCopy.titulo}</h2><p>{instagramCopy.texto}</p><a className="btn cream" href={negocio.redes.instagram} target="_blank" rel="noopener noreferrer">{instagramCopy.boton} ↗</a></div><div className="instagram-preview" aria-hidden="true"><span>{brandingConfig.initials}</span><span>♡</span><span>✦</span></div></div></section>}

  <section className="community-signup section"><div className="container community-grid"><div><span className="kicker">{communityCopy.kicker}</span><h2>{communityCopy.titulo}</h2><p>{communityCopy.texto}</p></div><form className="community-form" onSubmit={(event)=>event.preventDefault()}><label>Nombre<input type="text" name="nombre" placeholder="Tu nombre" autoComplete="name"/></label><label>WhatsApp o correo<input type="text" name="contacto" placeholder="Tu WhatsApp o correo" autoComplete="email"/></label><fieldset><legend>¿Qué te interesa conocer?</legend><div>{categories.filter(item=>item!=='Todos').map(item=><label key={item}><input type="checkbox" name="intereses" value={item}/>{item}</label>)}</div></fieldset><button type="button" aria-describedby="community-form-status">{communityCopy.boton}</button><small id="community-form-status">{communityCopy.estado} No almacenamos estos datos actualmente.</small></form></div></section>

  <section className="news-section section"><div className="container"><div className="center-head"><span className="kicker">{newsCopy.kicker}</span><h2>{newsCopy.titulo}</h2><p>{newsCopy.descripcion}</p></div>{(newsCopy.items||[]).filter(item=>item.activo!==false).length>0?<div className="news-grid">{newsCopy.items.filter(item=>item.activo!==false).map(item=><article key={`${item.titulo}-${item.fecha||''}`}>{item.imagen&&<img src={optimizedImage(item.imagen)} alt={item.titulo} loading="lazy" decoding="async"/>}<div><small>{item.fecha}</small><h3>{item.titulo}</h3><p>{item.texto}</p></div></article>)}</div>:<div className="news-grid placeholders">{(newsCopy.tipos||[]).map(item=><article key={item.titulo}><span aria-hidden="true">{item.icono}</span><div><small>Espacio preparado</small><h3>{item.titulo}</h3><p>{item.texto}</p></div></article>)}</div>}</div></section>

  <section id="contacto" className="visit"><div className="container visit-grid"><div className="visit-info"><span className="kicker light">{contact.kicker}</span><h2>{contact.titulo}</h2><div className="visit-details"><div className="info-row"><span>⌖</span><div><small>{contact.direccion_etiqueta}</small><b>{negocio.direccion}</b></div></div><div className="info-row"><span>◷</span><div><small>{contact.horarios_etiqueta}</small><b>{negocio.horarios.semana}</b><b>{negocio.horarios.domingo}</b></div></div><a className="visit-map-link" href={`https://maps.google.com/?q=${encodeURIComponent(negocio.direccion)}`} target="_blank" rel="noopener noreferrer">{contact.mapa_boton} →</a></div><a className="btn cream" href={wa(`Hola ${businessName}, quisiera hacer una consulta.`)} target="_blank">{contact.whatsapp_boton} ↗</a></div><iframe title="Mapa de ubicación" src={contact.mapa_url||`https://www.google.com/maps?q=${encodeURIComponent(negocio.direccion)}&output=embed`} loading="lazy"/></div></section>

  <section className="final-cta"><div className="container final-cta-inner"><div><span className="kicker light">{finalCta.kicker}</span><h2>{finalCta.titulo}</h2><p>{finalCta.texto}</p></div><div className="final-cta-actions"><a className="btn cream" href="#catalogo">{finalCta.catalogo} →</a><a className="btn final-wa" href={wa(`Hola ${businessName}, quisiera consultar disponibilidad y hacer un pedido.`)} target="_blank" rel="noopener noreferrer">{finalCta.whatsapp} ↗</a></div></div></section>

  <footer><div className="container footer-grid"><div className="brand footer-brand">{negocio.logo?<img className="brand-logo" src={optimizedImage(negocio.logo)} alt="" loading="lazy" decoding="async"/>:<span className="brand-mark">{brandingConfig.initials}</span>}<span><b>{businessName}</b><small>{footerCopy.descriptor}</small></span></div><p>{footerCopy.texto||negocio.descripcion}</p><div className="footer-links"><a href="#sabores">{nav.sabores}</a><a href="#catalogo">{nav.catalogo}</a><a href="#nosotros">{nav.nosotros}</a><a href="#contacto">{nav.contacto}</a>{socialLinks.map(([label,url])=><a key={label} href={url} target="_blank" rel="noopener noreferrer">{label} ↗</a>)}</div></div><div className="container copyright">© 2026 {businessName} <span>{negocio.direccion}</span></div></footer>
  <button type="button" className="chat-fab" onClick={()=>{if(!chat)trackEvent(MEASUREMENT_EVENTS.CHATBOT_OPEN,{location:'pagina'});setChat(!chat)}} aria-label={chat?'Cerrar asistente':'Abrir asistente'} aria-expanded={chat} aria-controls="cielito-chat">{chat?'✕':'☁'}<span>{chatCopy.boton}</span></button>
  {chat&&<aside id="cielito-chat" className="chatbox" role="dialog" aria-label={`Asistente ${assistantName}`}><header><div><span aria-hidden="true">☁</span><p><b>{assistantName}</b><small>{ui.asistente_de} {businessName}</small></p></div><button type="button" onClick={()=>setChat(false)} aria-label="Cerrar asistente">✕</button></header><div className="chat-body"><div className="bubble" aria-live="polite">{answer||welcomeMessage}</div><p className="chat-label">{chatCopy.preguntas_titulo}</p><div className="quick">{quickQuestions.map(question=><button type="button" key={question.key} className={answerKey===question.key?'active':''} aria-pressed={answerKey===question.key} onClick={()=>chooseChatOption(question)}>{question.label}</button>)}</div>{activeChatActions.length>0&&<div className="chat-actions"><span>Siguiente paso</span>{activeChatActions.filter(([,href])=>href).map(([label,href,closeChat])=><a key={label} href={href} target={href.startsWith('http')?'_blank':undefined} rel={href.startsWith('http')?'noopener noreferrer':undefined} onClick={closeChat?()=>setChat(false):undefined}>{label} →</a>)}</div>}</div><a className="chat-wa" href={wa(`Hola ${businessName}, necesito ayuda con mi pedido.`)} target="_blank" rel="noopener noreferrer">{chatCopy.whatsapp_boton} ↗</a></aside>}
 </main>
}

