import { useState } from 'react';

const sections = [
  ['general', 'Información y narrativa', 'Portada, descripción, historia e imágenes', '◫'],
  ['social', 'Redes sociales', 'Instagram y Facebook', '◎'],
  ['contact', 'Contacto y ubicación', 'Teléfonos, dirección y horarios', '⌖'],
  ['appearance', 'Apariencia', 'Colores principales de la página pública', '◐'],
  ['chatbot', 'Chatbot', 'Asistente y respuestas frecuentes', '☁'],
];

export default function BusinessSettings({ config, setConfig, answers, setAnswers, onSave, onSaveAnswers, onUpload, busy }) {
  const [active, setActive] = useState(null);
  const update = (key, value) => setConfig((current) => ({ ...current, [key]: value }));

  return <div className="settings-page">
    <div className="settings-intro"><div><span>Configuración central</span><h2>Configuración del negocio</h2><p>Administra la información que aparece en la página pública desde un solo lugar.</p></div><div className="settings-live"><i/> Cambios conectados a la web</div></div>
    {!active && <div className="settings-grid">{sections.map(([id, title, description, icon]) => <article key={id} className="settings-card"><div className="settings-icon">{icon}</div><div><h3>{title}</h3><p>{description}</p></div><button onClick={() => setActive(id)}>Editar →</button></article>)}</div>}
    {active && <section className="admin-card settings-editor"><button className="back-button" onClick={() => setActive(null)}>← Volver a configuración</button><div className="card-title"><div><h2>{sections.find((item) => item[0] === active)?.[1]}</h2><p>{sections.find((item) => item[0] === active)?.[2]}</p></div></div>
      {active === 'general' && <form className="cms-form" onSubmit={onSave}><Field label="Nombre del negocio" value={config.nombre} onChange={(v) => update('nombre', v)}/><Field label="Descripción corta" value={config.descripcion} onChange={(v) => update('descripcion', v)}/><Field label="Frase principal" value={config.hero_titulo} onChange={(v) => update('hero_titulo', v)}/><Field label="Frase destacada" value={config.hero_destacado} onChange={(v) => update('hero_destacado', v)}/><Field wide textarea label="Historia real del negocio" value={config.historia} onChange={(v) => update('historia', v)}/><Field wide textarea label="Conexión con Venezuela" value={config.historia_venezolana} onChange={(v) => update('historia_venezolana', v)}/><Field wide label="Categorías destacadas (separadas por comas)" value={config.categorias_destacadas} onChange={(v) => update('categorias_destacadas', v)}/><ImageField label="Logo" value={config.logo} onChange={(file) => onUpload(file, 'configuracion', 'logo')}/><ImageField label="Imagen principal" value={config.imagen_portada} onChange={(file) => onUpload(file, 'configuracion', 'imagen_portada')}/><p className="field-help wide">Completa la historia con hechos reales del negocio. La página no inventará fechas, lugares ni experiencias migratorias.</p><Save busy={busy}/></form>}
      {active === 'contact' && <form className="cms-form" onSubmit={onSave}><Field label="WhatsApp" value={config.whatsapp} onChange={(v) => update('whatsapp', v)}/><Field label="Teléfono" value={config.telefono} onChange={(v) => update('telefono', v)}/><Field wide label="Dirección" value={config.direccion} onChange={(v) => update('direccion', v)}/><Field label="Horario semana" value={config.horario_semana} onChange={(v) => update('horario_semana', v)}/><Field label="Horario domingo" value={config.horario_domingo} onChange={(v) => update('horario_domingo', v)}/><Save busy={busy}/></form>}
      {active === 'social' && <form className="cms-form" onSubmit={onSave}><Field label="Instagram" value={config.instagram} onChange={(v) => update('instagram', v)}/><Field label="Facebook" value={config.facebook} onChange={(v) => update('facebook', v)}/><p className="field-help wide">Los enlaces vacíos se ocultan automáticamente en la página pública.</p><Save busy={busy}/></form>}
      {active === 'appearance' && <form className="cms-form color-form" onSubmit={onSave}><ColorField label="Color principal · Azul profundo" value={config.color_principal} onChange={(v) => update('color_principal', v)}/><ColorField label="Color secundario · Rojo cálido" value={config.color_secundario} onChange={(v) => update('color_secundario', v)}/><ColorField label="Color de fondo · Crema maíz" value={config.color_fondo} onChange={(v) => update('color_fondo', v)}/><div className="palette-preview wide"><span style={{background: config.color_principal}}/><span style={{background: config.color_secundario}}/><span style={{background: config.color_fondo}}/></div><Save busy={busy}/></form>}
      {active === 'chatbot' && <div><form className="cms-form" onSubmit={onSave}><Field label="Nombre del asistente" value={config.chatbot_nombre} onChange={(v) => update('chatbot_nombre', v)}/><Field label="Mensaje inicial" value={config.chatbot_mensaje} onChange={(v) => update('chatbot_mensaje', v)}/><Save busy={busy}/></form><div className="chat-editor settings-chat">{answers.map((answer, index) => <label key={answer.id || answer.clave}>{answer.clave}<textarea value={answer.respuesta} onChange={(event) => setAnswers(answers.map((item, itemIndex) => itemIndex === index ? { ...item, respuesta: event.target.value } : item))}/></label>)}</div><button className="cms-primary" onClick={onSaveAnswers}>Guardar respuestas frecuentes</button></div>}
    </section>}
  </div>;
}

function Field({ label, value = '', onChange, textarea = false, wide = false }) { const Tag = textarea ? 'textarea' : 'input'; return <label className={wide ? 'wide' : ''}>{label}<Tag value={value || ''} onChange={(event) => onChange(event.target.value)}/></label> }
function ImageField({ label, value, onChange }) { return <label>{label}<input type="file" accept="image/*" onChange={(event) => event.target.files[0] && onChange(event.target.files[0])}/>{value && <img className="settings-image-preview" src={value} alt={`Vista previa de ${label}`}/>}</label> }
function ColorField({ label, value, onChange }) { return <label className="color-field">{label}<span><input type="color" value={value || '#000000'} onChange={(event) => onChange(event.target.value)}/><input value={value || ''} onChange={(event) => onChange(event.target.value)}/></span></label> }
function Save({ busy }) { return <button className="cms-primary wide" disabled={busy}>{busy ? 'Guardando…' : 'Guardar cambios'}</button> }
