import {useEffect,useMemo,useState} from 'react';
import {MEASUREMENT_EVENT_SIGNAL,readMeasurementEvents} from '../utils/measurement.js';
import {generateCielitoInsights} from '../utils/cielitoInsights.js';

export default function CielitoInsights({products=[]}){const [events,setEvents]=useState(()=>readMeasurementEvents());useEffect(()=>{const refresh=()=>setEvents(readMeasurementEvents());window.addEventListener(MEASUREMENT_EVENT_SIGNAL,refresh);window.addEventListener('storage',refresh);return()=>{window.removeEventListener(MEASUREMENT_EVENT_SIGNAL,refresh);window.removeEventListener('storage',refresh)}},[]);const report=useMemo(()=>generateCielitoInsights(events,products),[events,products]);return <div className="cielito-insights">
 <section className="analytics-intro"><div><span>Información comercial anónima</span><h2>Cielito Insights</h2><p>Conoce intereses generales detectados por el asistente. Solo se muestran conteos agregados: no se almacenan conversaciones, personas ni identificadores.</p></div></section>
 <div className="analytics-metrics"><article><span>Consultas detectadas</span><b>{report.totalQuestions}</b><small>Agrupadas por intención</small></article><article><span>Intenciones de compra</span><b>{report.purchaseIntents}</b><small>Señales anónimas en Cielito</small></article><article><span>Productos consultados</span><b>{report.products.length}</b><small>Solo visibles y disponibles</small></article><article><span>Categorías con interés</span><b>{report.categories.length}</b><small>Derivadas del catálogo vigente</small></article></div>
 <div className="cielito-insights-grid"><Ranking title="Consultas por intención" description="Tipos de ayuda solicitada" items={report.intents}/><Ranking title="Productos más consultados" description="Excluye agotados y ocultos" items={report.products}/><Ranking title="Categorías con mayor interés" description="Interés agregado del catálogo" items={report.categories}/><Ranking title="Preguntas frecuentes detectadas" description="Agrupadas por intención, sin mensajes" items={report.frequentQuestions}/></div>
 <section className="admin-card insights-recommendations"><div className="card-title"><div><h2>Sugerencias internas</h2><p>Orientaciones informativas; no realizan acciones automáticas.</p></div></div>{report.recommendations.length?<ul>{report.recommendations.map(item=><li key={item}>{item}</li>)}</ul>:<div className="empty-state">Aún no hay suficientes eventos anónimos para generar sugerencias.</div>}</section>
 <p className="analytics-note">Datos agregados · Sin mensajes completos · Sin perfiles individuales · Sin servicios externos</p>
 </div>}
function Ranking({title,description,items}){return <section className="admin-card insights-ranking"><div className="card-title"><div><h2>{title}</h2><p>{description}</p></div></div>{items.length?<ol>{items.slice(0,5).map(([label,count],index)=><li key={label}><span>{index+1}</span><b>{label}</b><strong>{count}</strong></li>)}</ol>:<div className="empty-state">Sin información disponible todavía.</div>}</section>}
