import { useMemo } from 'react';

const pageFields = [
  ['navegacion.inicio','Menú: Inicio'],['navegacion.sabores','Menú: Sabores'],['navegacion.catalogo','Menú: Catálogo'],['navegacion.nosotros','Menú: Nosotros'],['navegacion.contacto','Menú: Contacto'],['navegacion.pedido','Menú: Pedido'],
  ['interfaz.retiro','Texto retiro'],['interfaz.hecho','Texto sello'],['interfaz.con_carino','Texto inferior sello'],['interfaz.pedir','Acción pedir'],['interfaz.disponible','Estado disponible'],['interfaz.agotado','Estado agotado'],
  ['hero.eyebrow','Texto superior'],['hero.titulo','Título principal'],['hero.destacado','Texto destacado'],['hero.texto','Subtítulo'],
  ['hero.boton_catalogo','Botón catálogo'],['hero.boton_whatsapp','Botón WhatsApp'],['hero.confianza_titulo','Título confianza'],['hero.confianza_texto','Texto confianza'],['hero.tarjeta_titulo','Título tarjeta portada'],['hero.tarjeta_texto','Texto tarjeta portada'],['destacados.kicker','Etiqueta destacados'],['destacados.titulo','Título destacados'],['destacados.enlace','Enlace destacados'],
  ['recomendacion.kicker','Etiqueta recomendación'],['recomendacion.titulo','Título recomendación'],['recomendacion.texto','Texto recomendación'],['recomendacion.boton','Botón recomendación'],
  ['promociones.kicker','Etiqueta promociones'],['promociones.titulo','Título promociones'],['promociones.boton','Botón promociones'],['catalogo.kicker','Etiqueta catálogo'],['catalogo.titulo','Título catálogo'],['catalogo.descripcion','Descripción catálogo']
];
const aboutFields = [['nosotros.kicker','Etiqueta'],['nosotros.titulo','Título'],['nosotros.historia','Historia del negocio'],['nosotros.texto_secundario','Texto complementario'],['nosotros.firma','Firma'],['nosotros.cita','Cita destacada'],['venezuela.titulo','Título cultural'],['venezuela.descripcion','Descripción cultural'],['venezuela.texto_secundario','Historia venezolana']];
const contactFields = [['contacto.kicker','Etiqueta'],['contacto.titulo','Título'],['contacto.direccion_etiqueta','Etiqueta dirección'],['contacto.horarios_etiqueta','Etiqueta horarios'],['contacto.mapa_boton','Texto botón mapa'],['contacto.whatsapp_boton','Texto botón WhatsApp'],['contacto.mapa_url','URL de mapa embebido']];

const read = (object, path) => path.split('.').reduce((value, key) => value?.[key], object) ?? '';
const write = (object, path, value) => { const clone = structuredClone(object); const keys = path.split('.'); let cursor = clone; keys.slice(0,-1).forEach((key) => { cursor[key] = cursor[key] || {}; cursor = cursor[key]; }); cursor[keys.at(-1)] = value; return clone; };

export default function CmsSectionEditor({ mode, config, setConfig, answers, setAnswers, onSave, onSaveAnswers, onDeleteAnswer, onNotify, onUpload, busy }) {
  const content = useMemo(() => config.contenido_pagina || {}, [config.contenido_pagina]);
  const updateContent = (path, value) => setConfig((current) => ({ ...current, contenido_pagina: write(current.contenido_pagina || {}, path, value) }));
  const update = (key, value) => setConfig((current) => ({ ...current, [key]: value }));

  if (mode === 'pagina') return <EditorShell title="Página principal" description="Edita la portada, llamados a la acción y presentación del catálogo."><form className="cms-form" onSubmit={onSave}>{pageFields.map(([path,label]) => <Field key={path} label={label} value={read(content,path)} textarea={path.endsWith('.texto') || path.endsWith('.descripcion')} onChange={(value) => updateContent(path,value)}/>)}<div className="wide cms-array-editor"><h3>Indicadores de confianza</h3>{(content.beneficios||[]).map((item,index)=><div key={index}><Field label="Icono" value={item.icono} onChange={(value)=>updateContent(`beneficios.${index}.icono`,value)}/><Field label="Título" value={item.titulo} onChange={(value)=>updateContent(`beneficios.${index}.titulo`,value)}/><Field label="Texto" value={item.texto} onChange={(value)=>updateContent(`beneficios.${index}.texto`,value)}/></div>)}</div><ImageField label="Imagen de portada" value={config.imagen_portada} onChange={(file) => onUpload(file,'pagina','imagen_portada')}/><ImageField label="Imagen recomendación" value={read(content,'recomendacion.imagen')} onChange={async(file) => updateContent('recomendacion.imagen',await onUpload(file,'pagina','contenido_imagen',true))}/><Save busy={busy}/></form></EditorShell>;

  if (mode === 'nosotros') return <EditorShell title="Nosotros" description="Cuenta la historia real del negocio y su conexión con Venezuela."><form className="cms-form" onSubmit={onSave}>{aboutFields.map(([path,label]) => <Field key={path} label={label} value={read(content,path)} textarea onChange={(value) => updateContent(path,value)}/>)}<div className="wide cms-array-editor"><h3>Testimonios</h3>{(content.testimonios?.items||[]).map((item,index)=><div key={index}><Field label="Testimonio" value={item.texto} onChange={(value)=>updateContent(`testimonios.items.${index}.texto`,value)}/><Field label="Nombre" value={item.nombre} onChange={(value)=>updateContent(`testimonios.items.${index}.nombre`,value)}/><Field label="Detalle" value={item.detalle} onChange={(value)=>updateContent(`testimonios.items.${index}.detalle`,value)}/></div>)}</div><ImageField label="Imagen sección Nosotros" value={read(content,'nosotros.imagen')} onChange={async(file) => updateContent('nosotros.imagen',await onUpload(file,'pagina','contenido_imagen',true))}/><Save busy={busy}/></form></EditorShell>;

  if (mode === 'diseno') return <EditorShell title="Diseño" description="Personaliza la identidad visual sin editar hojas de estilo."><form className="cms-form color-form" onSubmit={onSave}><ImageField label="Logo" value={config.logo} onChange={(file) => onUpload(file,'configuracion','logo')}/><Color label="Color principal" value={config.color_principal} onChange={(value) => update('color_principal',value)}/><Color label="Color secundario" value={config.color_secundario} onChange={(value) => update('color_secundario',value)}/><Color label="Color de fondo" value={config.color_fondo} onChange={(value) => update('color_fondo',value)}/><Color label="Color destacado" value={config.color_destacado} onChange={(value) => update('color_destacado',value)}/><Field label="Descriptor de marca" value={read(content,'footer.descriptor')} onChange={(value) => updateContent('footer.descriptor',value)}/><Field label="Texto del pie de página" value={read(content,'footer.texto')} textarea onChange={(value) => updateContent('footer.texto',value)}/><Save busy={busy}/></form></EditorShell>;

  if (mode === 'contacto') return <EditorShell title="Contacto" description="Mantén actualizados ubicación, horarios y canales de atención."><form className="cms-form" onSubmit={onSave}><Field label="Dirección" value={config.direccion} onChange={(value) => update('direccion',value)}/><Field label="WhatsApp" value={config.whatsapp} onChange={(value) => update('whatsapp',value)}/><Field label="Teléfono" value={config.telefono} onChange={(value) => update('telefono',value)}/><Field label="Horario semana" value={config.horario_semana} onChange={(value) => update('horario_semana',value)}/><Field label="Horario domingo" value={config.horario_domingo} onChange={(value) => update('horario_domingo',value)}/><Field label="Instagram" value={config.instagram} onChange={(value) => update('instagram',value)}/><Field label="Facebook" value={config.facebook} onChange={(value) => update('facebook',value)}/><Field label="TikTok" value={config.tiktok} onChange={(value) => update('tiktok',value)}/>{contactFields.map(([path,label]) => <Field key={path} label={label} value={read(content,path)} onChange={(value) => updateContent(path,value)}/>)}<Save busy={busy}/></form></EditorShell>;

  const questions = content.chatbot?.preguntas || [];
  const addQuestion = () => updateContent('chatbot.preguntas', [...questions, { label: '', key: '' }]);
  const removeQuestion = (index) => { updateContent('chatbot.preguntas', questions.filter((_, itemIndex) => itemIndex !== index)); onNotify('Pregunta eliminada. Guarda los cambios para publicarla'); };
  const saveChatbot = (event) => {
    const normalized = questions.map((item) => ({ label: item.label?.trim(), key: item.key?.trim() }));
    if (normalized.some((item) => !item.label || !item.key)) { event.preventDefault(); return onNotify('La pregunta y su clave son obligatorias'); }
    const keys = normalized.map((item) => item.key);
    if (new Set(keys).size !== keys.length) { event.preventDefault(); return onNotify('No se permiten claves duplicadas'); }
    if (normalized.some((item) => !answers.some((answer) => answer.clave?.trim() === item.key))) { event.preventDefault(); return onNotify('Cada pregunta debe usar la clave de una respuesta existente'); }
    onNotify('Pregunta creada correctamente');
    return onSave(event);
  };
  const addAnswer = () => setAnswers((current) => [...current, { clave: '', respuesta: '' }]);
  const focusFirstField = (event) => event.currentTarget.closest('.cms-manage-row')?.querySelector('input, textarea')?.focus();

  return <EditorShell title="Chatbot" description="Edita el asistente y todas sus respuestas sin tocar código."><form className="cms-form" onSubmit={saveChatbot}><Field label="Nombre del asistente" value={config.chatbot_nombre} onChange={(value) => update('chatbot_nombre',value)}/><Field label="Mensaje inicial" value={config.chatbot_mensaje} textarea onChange={(value) => update('chatbot_mensaje',value)}/><Field label="Texto del botón flotante" value={read(content,'chatbot.boton')} onChange={(value) => updateContent('chatbot.boton',value)}/><Field label="Título preguntas rápidas" value={read(content,'chatbot.preguntas_titulo')} onChange={(value) => updateContent('chatbot.preguntas_titulo',value)}/><div className="wide cms-array-editor"><div className="card-title"><h3>Preguntas rápidas</h3><button type="button" onClick={addQuestion}>＋ Nueva pregunta rápida</button></div>{questions.map((item,index)=><div className="cms-manage-row" key={index}><Field label="Etiqueta" value={item.label} onChange={(value)=>updateContent(`chatbot.preguntas.${index}.label`,value)}/><Field label="Clave de respuesta" value={item.key} onChange={(value)=>updateContent(`chatbot.preguntas.${index}.key`,value)}/><div className="row-actions"><button type="button" onClick={focusFirstField}>Editar</button><button type="button" onClick={()=>removeQuestion(index)}>Eliminar</button></div></div>)}</div><Save busy={busy}/></form><div className="wide cms-array-editor"><div className="card-title"><h3>Respuestas del chatbot</h3><button type="button" onClick={addAnswer}>＋ Nueva respuesta</button></div>{answers.map((answer,index)=><div className="cms-manage-row" key={answer.id||`new-${index}`}><Field label="Clave" value={answer.clave} onChange={(value)=>setAnswers((current)=>current.map((item,itemIndex)=>itemIndex===index?{...item,clave:value}:item))}/><Field label="Respuesta" value={answer.respuesta} textarea onChange={(value)=>setAnswers((current)=>current.map((item,itemIndex)=>itemIndex===index?{...item,respuesta:value}:item))}/><div className="row-actions"><button type="button" onClick={focusFirstField}>Editar</button><button type="button" onClick={()=>onDeleteAnswer(answer,index)}>Eliminar</button></div></div>)}</div><button className="cms-primary" onClick={onSaveAnswers}>Guardar respuestas</button></EditorShell>;
}

function EditorShell({title,description,children}){return <div className="cms-section-page"><div className="cms-section-intro"><span>Editor visual</span><h2>{title}</h2><p>{description}</p></div><section className="admin-card">{children}</section></div>}
function Field({label,value='',onChange,textarea=false}){const Tag=textarea?'textarea':'input';return <label className={textarea?'wide':''}>{label}<Tag value={value||''} onChange={(event)=>onChange(event.target.value)}/></label>}
function ImageField({label,value,onChange}){return <label>{label}<input type="file" accept="image/*" onChange={(event)=>event.target.files[0]&&onChange(event.target.files[0])}/>{value&&<img className="settings-image-preview" src={value} alt={`Vista previa de ${label}`}/>}</label>}
function Color({label,value,onChange}){return <label className="color-field">{label}<span><input type="color" value={value||'#000000'} onChange={(event)=>onChange(event.target.value)}/><input value={value||''} onChange={(event)=>onChange(event.target.value)}/></span></label>}
function Save({busy}){return <button className="cms-primary wide" disabled={busy}>{busy?'Guardando…':'Guardar y publicar cambios'}</button>}
